INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Andres', 'Guzman', 'Debito', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('John', 'Doe', 'Credito', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Pepa', 'Doe', 'Debito', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Luna', 'Garcia', 'Debito', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Lucy', 'Martinez', 'Credito', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('John', 'Roe', 'PayPal', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Lou', 'Loe', 'PayPal', NULL, NULL);
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Lalo', 'Mena', 'Webpay', '2025-09-28 20:10:05.658', '2025-09-28 20:11:49.617');
INSERT INTO public.clients ("name", surname, payment_type, created_at, updated_at) VALUES('Pia', 'Perez', 'PayPal Plus', '2025-09-28 20:21:00.272', '2025-09-28 20:21:47.109');
INSERT INTO public.students("name", surname) VALUES('Johana', 'Doe');
INSERT INTO public.students("name", surname) VALUES('Pepe', 'Gon');
INSERT INTO public.courses("name", professor) VALUES('Curso Spring', 'Andres');
INSERT INTO public.courses("name", professor) VALUES('Curso Java EE 9', 'Andres');
INSERT INTO public.addresses(street, "number") VALUES('Vaticano', 123);
INSERT INTO public.addresses(street, "number") VALUES('Colón', 456);
INSERT INTO public.tbl_clients_addresses(id_client, id_address) VALUES(1, 1);
INSERT INTO public.tbl_clients_addresses(id_client, id_address) VALUES(1, 2);
